### ISSUE TITLE
Bookmarks don't work with current MoBIE beta

### ISSUE THREAD

**Issue by constantinpape** [mobie/covid-tomo-datasets#2]
The bookmakrs for individual tomograms don't work any more in the current mobie-beta.

This is the first bookmark for  the default dataset in the "regular" MoBIE:
![bkmrk-tomo1](https://user-images.githubusercontent.com/4263537/93504007-26486a00-f919-11ea-8ecd-aa14319ef8a2.png)

This is the bookmark in MoBIE-beta:
![bkmrk-tomo2](https://user-images.githubusercontent.com/4263537/93504053-395b3a00-f919-11ea-9319-1b882df434c1.png)

I scrolled around a bit and it looks like only the z-position is off.

@tischi I was considering to change the bookmarks to normed views anyways, but it would be good to know why there is this difference between versions.

**Comment by constantinpape** [comment]
@tischi did you also change how centering works for the normal views (i.e. central pixel vs. corner pixels)? If so that might explain the difference and we don't need to fix it.

**Comment by tischi** [comment]
> did you also change how centering works for the normal views (i.e. central pixel vs. corner pixels)? If so that might explain the difference and we don't need to fix it.

I did not change anything knowingly...
I will have a look.

**Comment by tischi** [comment]
I don't know what is going on. It is a little bit off in z indeed. This could also be due to some subtle changes in BDV itself....
I tried recording a normalised transform and that worked well.
Not sure, should we just ignore this and proceed?

**Comment by constantinpape** [comment]
> I don't know what is going on. It is a little bit off in z indeed. This could also be due to some subtle changes in BDV itself....
> I tried recording a normalised transform and that worked well.
> Not sure, should we just ignore this and proceed?

Yes, let's just ignore it and proceed. I will replace the bookmarks with normalized ones (wanted to do this anyway).

**Comment by constantinpape** [comment]
Ok, I have added normed bookmarks. Will merge them in #6 as soon as we have the mobie version compatible with it.
