### ISSUE TITLE
Position logging / moving not working as expected

### ISSUE THREAD

**Issue by constantinpape** [mobie/covid-tomo-datasets#3]
Reported by Paolo and Giulia

**Comment by paoloronchi** [comment]
the following functions did not work:
1) move to a position, using previously logged coordinates
2) log new positions

**Comment by constantinpape** [comment]
I cannot reproduce this. I can follow your description and still log a new position, see below.
Are you doing something different than me?
(Note that this is a slightly newer version than on the normal MoBIE update site, but for me it also worked with the version from the normal update site).

![ezgif com-crop](https://user-images.githubusercontent.com/4263537/93513026-82b18680-f925-11ea-8bed-cbadb6ed973f.gif)

**Comment by giuliamizzon** [comment]
Hi Constantin, thanks for opening the case for us.
The difference from your video for us is that the right clicking in the viewer, as you do in the video, did not open the dropdown menu where you can choose to log the position.
Likewise, copying a string of numbers from the table into the location field and clicking move did not work. 
We can copy the text in, but nothing happens after we click move.
Both things were working until before the update.

**Comment by constantinpape** [comment]
Thanks for clarifying. This should be fixed with the new update tomorrow.
We will let you know when it's there.
